# Generated by Django 4.2.30 on 2026-10-01 03:31

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderCrossing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=96, verbose_name='название (рус.)')),
                ('name_zh', models.CharField(max_length=96, verbose_name='название (кит.)')),
                ('mode', models.CharField(choices=[('road', 'Автомобильный'), ('rail', 'Железнодорожный'), ('sea', 'Морской'), ('air', 'Воздушный')], default='road', max_length=8, verbose_name='вид транспорта')),
                ('capacity_t_per_day', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True, verbose_name='пропускная способность, т/сут')),
                ('dwell_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='среднее время пребывания, сут')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crossings', to='catalog.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'пункт пропуска',
                'verbose_name_plural': 'пункты пропуска',
                'db_table': 'portal_bordercrossing',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='номер')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='количество')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='масса, кг')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='объём, м³')),
                ('ship_date', models.DateField(blank=True, null=True, verbose_name='дата отгрузки')),
                ('container_no', models.CharField(blank=True, max_length=16, verbose_name='номер контейнера')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='trading.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'партия',
                'verbose_name_plural': 'партии',
                'db_table': 'portal_shipment',
                'ordering': ['-created_at'],
            },
            bases=(core.models.DocNumberMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4,12}$')], verbose_name='код ТН ВЭД')),
                ('duty_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='пошлина, %')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='НДС, %')),
                ('valid_from', models.DateField(verbose_name='действует с')),
            ],
            options={
                'verbose_name': 'таможенный тариф',
                'verbose_name_plural': 'таможенные тарифы',
                'db_table': 'portal_tariff',
                'ordering': ['hs_code'],
            },
        ),
        migrations.CreateModel(
            name='TransportLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('mode', models.CharField(choices=[('road', 'Автомобильный'), ('rail', 'Железнодорожный'), ('sea', 'Морской'), ('air', 'Воздушный')], default='road', max_length=8, verbose_name='вид транспорта')),
                ('days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='сроки доставки, сут')),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='стоимость, за кг')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lanes_to', to='logistics.bordercrossing', verbose_name='пункт назначения')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lanes_from', to='logistics.bordercrossing', verbose_name='пункт отправления')),
            ],
            options={
                'verbose_name': 'логистический канал',
                'verbose_name_plural': 'логистические каналы',
                'db_table': 'portal_transportlane',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(blank=True, help_text='Заполняется, если перевозчик не зарегистрирован', max_length=128, verbose_name='название перевозчика')),
                ('mode', models.CharField(choices=[('road', 'Автомобильный'), ('rail', 'Железнодорожный'), ('sea', 'Морской'), ('air', 'Воздушный')], default='road', max_length=8, verbose_name='вид транспорта')),
                ('waybill_no', models.CharField(blank=True, max_length=32, verbose_name='транспортная накладная')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='стоимость перевозки')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='accounts.enterprise', verbose_name='перевозчик')),
                ('lane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='logistics.transportlane', verbose_name='канал')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='logistics.shipment', verbose_name='партия')),
            ],
            options={
                'verbose_name': 'перевозка',
                'verbose_name_plural': 'перевозки',
                'db_table': 'portal_transport',
            },
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(verbose_name='время события')),
                ('place', models.CharField(max_length=128, verbose_name='место')),
                ('status', models.CharField(max_length=64, verbose_name='статус')),
                ('note', models.CharField(blank=True, max_length=191, verbose_name='примечание')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_points', to='logistics.transport', verbose_name='перевозка')),
            ],
            options={
                'verbose_name': 'точка маршрута',
                'verbose_name_plural': 'точки маршрута',
                'db_table': 'portal_trackpoint',
                'ordering': ['transport', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='номер')),
                ('kind', models.CharField(choices=[('delay', 'Просрочка'), ('damage', 'Повреждение'), ('shortage', 'Недовоз'), ('customs', 'Таможня'), ('other', 'Прочее')], max_length=16, verbose_name='тип')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=8, verbose_name='критичность')),
                ('description', models.TextField(verbose_name='описание')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('in_progress', 'В работе'), ('resolved', 'Урегулирован'), ('closed', 'Закрыт')], default='registered', max_length=16, verbose_name='статус')),
                ('resolution', models.TextField(blank=True, verbose_name='результат')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL, verbose_name='заявитель')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='logistics.shipment', verbose_name='партия')),
            ],
            options={
                'verbose_name': 'инцидент',
                'verbose_name_plural': 'инциденты',
                'db_table': 'portal_incident',
                'ordering': ['-created_at'],
            },
            bases=(core.models.DocNumberMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='transportlane',
            constraint=models.CheckConstraint(check=models.Q(('origin', models.F('destination')), _negated=True), name='lane_origin_differs_destination'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity'], name='portal_inci_status_1d1678_idx'),
        ),
    ]
