# Generated by Django 4.2.30 on 2026-10-01 03:31

import core.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='номер')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='срок оплаты')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выставлен'), ('partial', 'Частично оплачен'), ('paid', 'Оплачен'), ('disputed', 'Оспаривается')], default='draft', max_length=16, verbose_name='статус')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='подтвердил')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='catalog.currency', verbose_name='валюта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='trading.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'счёт',
                'verbose_name_plural': 'счета',
                'db_table': 'portal_statement',
                'ordering': ['-created_at'],
            },
            bases=(core.models.DocNumberMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=191, verbose_name='назначение платежа')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('source', models.CharField(choices=[('order', 'Заказ'), ('transport', 'Перевозка'), ('duty', 'Таможня'), ('other', 'Прочее')], default='order', max_length=16, verbose_name='источник')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.statement', verbose_name='счёт')),
            ],
            options={
                'verbose_name': 'строка счёта',
                'verbose_name_plural': 'строки счетов',
                'db_table': 'portal_statementline',
                'ordering': ['statement', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=128, verbose_name='контрагент')),
                ('period', models.CharField(help_text='Например: 2026-09', max_length=16, verbose_name='период')),
                ('our_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='наша сумма')),
                ('partner_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма партнёра')),
                ('diff', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='разница')),
                ('status', models.CharField(choices=[('new', 'Начата'), ('in_progress', 'В работе'), ('resolved', 'Сверена')], default='new', max_length=16, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='trading.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'сверка расчётов',
                'verbose_name_plural': 'сверки расчётов',
                'db_table': 'portal_reconciliation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма')),
                ('channel_note', models.CharField(blank=True, max_length=191, verbose_name='канал и реквизиты')),
                ('buyer_confirmed', models.BooleanField(default=False, verbose_name='подтвердил закупщик')),
                ('supplier_confirmed', models.BooleanField(default=False, verbose_name='подтвердил поставщик')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.statement', verbose_name='счёт')),
            ],
            options={
                'verbose_name': 'регистрация платежа',
                'verbose_name_plural': 'регистрации платежей',
                'db_table': 'portal_payment',
                'ordering': ['-paid_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='statementline',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', Decimal('0')), ('qty__gt', Decimal('0'))), name='statementline_values_positive'),
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', Decimal('0'))), name='statement_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0'))), name='payment_amount_positive'),
        ),
    ]
