# Generated by Django 4.2.30 on 2026-10-01 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='ключ')),
                ('value', models.TextField(verbose_name='значение')),
                ('note', models.CharField(blank=True, max_length=191, verbose_name='назначение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
            ],
            options={
                'verbose_name': 'параметр системы',
                'verbose_name_plural': 'параметры системы',
                'db_table': 'portal_systemparam',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='действие')),
                ('target_kind', models.CharField(max_length=32, verbose_name='тип объекта')),
                ('target_id', models.CharField(max_length=32, verbose_name='код объекта')),
                ('before', models.TextField(blank=True, verbose_name='до изменения')),
                ('after', models.TextField(blank=True, verbose_name='после изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='событие')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='субъект')),
            ],
            options={
                'verbose_name': 'запись журнала',
                'verbose_name_plural': 'журнал действий',
                'db_table': 'portal_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_kind', 'created_at'], name='portal_audi_target__3bcd4f_idx')],
            },
        ),
    ]
