# Generated by Django 4.2.30 on 2026-10-01 03:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=96, verbose_name='название (рус.)')),
                ('name_zh', models.CharField(max_length=96, verbose_name='название (кит.)')),
                ('formula', models.CharField(blank=True, max_length=191, verbose_name='формула расчёта')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='единица')),
                ('period', models.CharField(choices=[('day', 'Сутки'), ('week', 'Неделя'), ('month', 'Месяц')], default='month', max_length=8, verbose_name='период')),
            ],
            options={
                'verbose_name': 'показатель',
                'verbose_name_plural': 'показатели',
                'db_table': 'portal_metric',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(help_text='Например: 2026-09', max_length=16, verbose_name='период')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='значение')),
                ('calculated_at', models.DateField(verbose_name='рассчитано')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analytics.metric', verbose_name='показатель')),
            ],
            options={
                'verbose_name': 'снимок показателя',
                'verbose_name_plural': 'снимки показателей',
                'db_table': 'portal_metricsnapshot',
                'ordering': ['-period_key'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64, verbose_name='вид риска')),
                ('probability', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='low', max_length=8, verbose_name='вероятность')),
                ('impact', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=8, verbose_name='ущерб')),
                ('level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='low', max_length=8, verbose_name='уровень')),
                ('advice', models.TextField(blank=True, verbose_name='рекомендация')),
                ('detected_at', models.DateField(default=django.utils.timezone.now, verbose_name='выявлен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='trading.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'риск соответствия',
                'verbose_name_plural': 'риски соответствия',
                'db_table': 'portal_compliancerisk',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='metricsnapshot',
            constraint=models.UniqueConstraint(fields=('metric', 'period_key'), name='metricsnapshot_unique'),
        ),
    ]
