# Generated by Django 4.2.30 on 2026-10-01 03:31

import core.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='номер')),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW'), ('FCA', 'FCA'), ('CPT', 'CPT'), ('CIF', 'CIF'), ('DAP', 'DAP'), ('DDP', 'DDP')], max_length=3, verbose_name='базис поставки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подписан'), ('in_production', 'Производство'), ('shipped', 'Отгружен'), ('completed', 'Завершён'), ('canceled', 'Отменён')], default='draft', max_length=16, verbose_name='статус')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='дата подписания')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_buyer', to='accounts.enterprise', verbose_name='закупщик')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.currency', verbose_name='валюта')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'portal_order',
                'ordering': ['-created_at'],
            },
            bases=(core.models.DocNumberMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='номер')),
                ('valid_until', models.DateField(verbose_name='действительно до')),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW'), ('FCA', 'FCA'), ('CPT', 'CPT'), ('CIF', 'CIF'), ('DAP', 'DAP'), ('DDP', 'DDP')], max_length=3, verbose_name='базис поставки')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('expired', 'Истекло'), ('withdrawn', 'Отозвано')], default='draft', max_length=16, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='catalog.currency', verbose_name='валюта')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложения',
                'db_table': 'portal_quote',
                'ordering': ['-created_at'],
            },
            bases=(core.models.DocNumberMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Rfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='номер')),
                ('title', models.CharField(max_length=191, verbose_name='заголовок')),
                ('due_date', models.DateField(verbose_name='срок ответа')),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW'), ('FCA', 'FCA'), ('CPT', 'CPT'), ('CIF', 'CIF'), ('DAP', 'DAP'), ('DDP', 'DDP')], default='FCA', max_length=3, verbose_name='базис поставки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Опубликован'), ('quoted', 'Есть предложения'), ('closed', 'Закрыт'), ('canceled', 'Отменён')], default='draft', max_length=16, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='accounts.enterprise', verbose_name='закупщик')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='catalog.currency', verbose_name='валюта')),
            ],
            options={
                'verbose_name': 'запрос котировки',
                'verbose_name_plural': 'запросы котировки',
                'db_table': 'portal_rfq',
                'ordering': ['-created_at'],
            },
            bases=(core.models.DocNumberMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RfqLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='количество')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='целевая цена')),
                ('requirement', models.CharField(blank=True, max_length=191, verbose_name='требование')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='catalog.good', verbose_name='товар')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='trading.rfq', verbose_name='запрос')),
            ],
            options={
                'verbose_name': 'позиция запроса',
                'verbose_name_plural': 'позиции запросов',
                'db_table': 'portal_rfqline',
                'ordering': ['rfq', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QuoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='номер версии')),
                ('changed_fields', models.CharField(blank=True, max_length=191, verbose_name='изменённые поля')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='пояснение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_versions', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='trading.quote', verbose_name='предложение')),
            ],
            options={
                'verbose_name': 'версия предложения',
                'verbose_name_plural': 'версии предложений',
                'db_table': 'portal_quoteversion',
                'ordering': ['quote', 'version'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('delivery_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='срок поставки, сут')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='catalog.good', verbose_name='товар')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='trading.quote', verbose_name='предложение')),
            ],
            options={
                'verbose_name': 'позиция предложения',
                'verbose_name_plural': 'позиции предложений',
                'db_table': 'portal_quoteline',
                'ordering': ['quote', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='trading.rfq', verbose_name='запрос'),
        ),
        migrations.AddField(
            model_name='quote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='accounts.enterprise', verbose_name='поставщик'),
        ),
        migrations.CreateModel(
            name='OrderMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contract', 'Подписание'), ('prepayment', 'Предоплата'), ('production', 'Производство'), ('packing', 'Упаковка'), ('shipment', 'Отгрузка'), ('customs', 'Таможня'), ('delivery', 'Передача'), ('payment', 'Расчёт')], max_length=16, verbose_name='вид этапа')),
                ('planned_date', models.DateField(verbose_name='плановая дата')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='фактическая дата')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Выполнен'), ('skipped', 'Пропущен')], default='pending', max_length=16, verbose_name='статус')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='trading.order', verbose_name='заказ')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
            ],
            options={
                'verbose_name': 'этап заказа',
                'verbose_name_plural': 'этапы заказов',
                'db_table': 'portal_ordermilestone',
                'ordering': ['order', 'planned_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('delivery_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='срок поставки, сут')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.good', verbose_name='товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='trading.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'позиция заказа',
                'verbose_name_plural': 'позиции заказов',
                'db_table': 'portal_orderline',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('scope', 'Состав'), ('dates', 'Сроки'), ('price', 'Цена'), ('address', 'Адрес'), ('other', 'Прочее')], max_length=16, verbose_name='тип изменения')),
                ('before', models.TextField(blank=True, verbose_name='было')),
                ('after', models.TextField(blank=True, verbose_name='стало')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_approved', to=settings.AUTH_USER_MODEL, verbose_name='согласовал')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_init', to=settings.AUTH_USER_MODEL, verbose_name='инициатор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='trading.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'изменение заказа',
                'verbose_name_plural': 'изменения заказов',
                'db_table': 'portal_orderchange',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.quote', verbose_name='предложение'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_supplier', to='accounts.enterprise', verbose_name='поставщик'),
        ),
        migrations.AddConstraint(
            model_name='rfqline',
            constraint=models.CheckConstraint(check=models.Q(('qty__gt', Decimal('0'))), name='rfqline_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status', 'due_date'], name='portal_rfq_status_1a0c79_idx'),
        ),
        migrations.AddConstraint(
            model_name='quoteversion',
            constraint=models.UniqueConstraint(fields=('quote', 'version'), name='quoteversion_unique'),
        ),
        migrations.AddConstraint(
            model_name='quoteline',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', Decimal('0')), ('qty__gt', Decimal('0'))), name='quoteline_values_positive'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', 'valid_until'], name='portal_quot_status_2e5a7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', Decimal('0'))), name='quote_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ordermilestone',
            constraint=models.UniqueConstraint(fields=('order', 'kind'), name='milestone_order_kind_unique'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', Decimal('0')), ('qty__gt', Decimal('0'))), name='orderline_values_positive'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='portal_orde_status_f263f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('buyer', models.F('supplier')), _negated=True), name='order_buyer_differs_supplier'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', Decimal('0'))), name='order_amount_non_negative'),
        ),
    ]
