# Generated by Django 4.2.30 on 2026-10-01 03:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name_ru', models.CharField(max_length=128, verbose_name='название (рус.)')),
                ('name_zh', models.CharField(blank=True, max_length=128, verbose_name='название (кит.)')),
                ('tin', models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН / код единой социальной лицензии')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='адрес')),
                ('bank_account', models.CharField(blank=True, max_length=64, verbose_name='банковский счёт')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('verifying', 'На проверке'), ('active', 'Активна'), ('blocked', 'Заблокирована')], default='new', max_length=16, verbose_name='статус')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enterprises', to='catalog.country', verbose_name='страна')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enterprises', to='catalog.industry', verbose_name='отрасль')),
            ],
            options={
                'verbose_name': 'предприятие',
                'verbose_name_plural': 'предприятия',
                'db_table': 'portal_enterprise',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('zh', '中文')], default='ru', max_length=2, verbose_name='язык интерфейса')),
                ('phone', models.CharField(blank=True, max_length=24, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s-]{7,20}$', 'Некорректный номер телефона')], verbose_name='телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
                'db_table': 'portal_profile',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Закупщик'), ('supplier', 'Поставщик'), ('logistics', 'Логист'), ('broker', 'Брокер'), ('finance', 'Бухгалтер'), ('admin', 'Администратор')], default='buyer', max_length=16, verbose_name='роль')),
                ('department', models.CharField(blank=True, max_length=64, verbose_name='подразделение')),
                ('joined_at', models.DateField(default=django.utils.timezone.now, verbose_name='дата вступления')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.enterprise', verbose_name='предприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'членство',
                'verbose_name_plural': 'членства',
                'db_table': 'portal_membership',
                'ordering': ['enterprise', 'role'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='код приглашения')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('role', models.CharField(choices=[('buyer', 'Закупщик'), ('supplier', 'Поставщик'), ('logistics', 'Логист'), ('broker', 'Брокер'), ('finance', 'Бухгалтер'), ('admin', 'Администратор')], max_length=16, verbose_name='роль')),
                ('valid_until', models.DateField(verbose_name='действительно до')),
                ('status', models.CharField(choices=[('pending', 'Отправлено'), ('accepted', 'Принято'), ('expired', 'Истекло'), ('revoked', 'Отозвано')], default='pending', max_length=16, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.enterprise', verbose_name='предприятие')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='пригласил')),
            ],
            options={
                'verbose_name': 'приглашение',
                'verbose_name_plural': 'приглашения',
                'db_table': 'portal_invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название партнёра')),
                ('contact_person', models.CharField(blank=True, max_length=96, verbose_name='контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=24, verbose_name='телефон')),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW'), ('FCA', 'FCA'), ('CPT', 'CPT'), ('CIF', 'CIF'), ('DAP', 'DAP'), ('DDP', 'DDP')], default='FCA', max_length=3, verbose_name='базис поставки')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparties', to='catalog.currency', verbose_name='валюта по умолчанию')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='accounts.enterprise', verbose_name='предприятие-инициатор')),
            ],
            options={
                'verbose_name': 'контрагент',
                'verbose_name_plural': 'контрагенты',
                'db_table': 'portal_counterparty',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'enterprise'), name='membership_user_enterprise_unique'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['status', 'country'], name='portal_ente_status_265899_idx'),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(fields=('enterprise', 'name'), name='counterparty_enterprise_name_unique'),
        ),
    ]
