"""
Django settings for tradehub project.

《Python Web 应用开发》课程设计。
应用：《面向中俄跨境贸易的轻量级协同工作
平台》— Web 客户端（服务器端）。

Generated by 'django-admin startproject' using Django 4.2.30.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# --- 安全---------------------------------------------------------
# 注意：该密钥仅用于教学开发。
SECRET_KEY = 'django-insecure-t$kr*a26xh2%=z1sin=@%l-q=9qqagn52%t_!wte2n3eyh_03z'

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# --- 应用-----------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 课程设计的应用
    'portal.apps.PortalConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    # 界面语言的自定义选择（?lang= -> 会话）。
    # 置于 SessionMiddleware 之后（会访问 request.session）
    # 以及 LocaleMiddleware 之后（否则它会覆盖所选语言区域）。
    'portal.middleware.LanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tradehub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # LANGUAGE_CODE / LANGUAGE_BIDI — 管理后台需要
                # 用于 lang 属性和文本方向。
                'django.template.context_processors.i18n',
                'portal.context_processors.navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'tradehub.wsgi.application'
ASGI_APPLICATION = 'tradehub.asgi.application'


# --- 数据库----------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# --- 认证-------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'NumericPasswordValidator',
    },
]

LOGIN_URL = 'portal:login'
LOGIN_REDIRECT_URL = 'portal:dashboard'
LOGOUT_REDIRECT_URL = 'portal:index'


# --- 国际化--------------------------------------------------
# 界面语言切换采用自有机制
# (portal/i18n.py + portal/labels.py + portal.middleware.LanguageMiddleware):
# 翻译来源为项目数据（页面注册表 portal/pages.py 与
# 标签字典 portal/labels.py），而非 .po/.mo 文件。
#
# 下面的 LANGUAGES 列表是管理后台所需的：其翻译包含
# 在 Django 发行包中，LanguageMiddleware 会激活对应的语言区域，
# 因此 /admin/ 会随同一语言选择切换。
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('ru', 'Русский'),
    ('zh-hans', '中文'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']


# --- 静态文件与媒体文件--------------------------------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
