"""
Django settings for tradehub project.

Курсовой проект по дисциплине «Разработка веб-приложений на Python».
Приложение: «Легковесная платформа совместной работы для трансграничной
торговли России и Китая» — веб-клиент (серверная часть).

Generated by 'django-admin startproject' using Django 4.2.30.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# --- Безопасность ---------------------------------------------------------
# ВНИМАНИЕ: ключ предназначен только для учебной разработки.
SECRET_KEY = 'django-insecure-t$kr*a26xh2%=z1sin=@%l-q=9qqagn52%t_!wte2n3eyh_03z'

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# --- Приложения -----------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # приложение курсового проекта
    'portal.apps.PortalConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    # Собственный выбор языка интерфейса (?lang= -> сессия).
    # Ставится после SessionMiddleware (обращается к request.session)
    # и после LocaleMiddleware (иначе тот перезапишет выбранную локаль).
    'portal.middleware.LanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tradehub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # LANGUAGE_CODE / LANGUAGE_BIDI — нужны административной панели
                # для атрибута lang и направления текста.
                'django.template.context_processors.i18n',
                'portal.context_processors.navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'tradehub.wsgi.application'
ASGI_APPLICATION = 'tradehub.asgi.application'


# --- База данных ----------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# --- Аутентификация -------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'NumericPasswordValidator',
    },
]

LOGIN_URL = 'portal:login'
LOGIN_REDIRECT_URL = 'portal:dashboard'
LOGOUT_REDIRECT_URL = 'portal:index'


# --- Интернационализация --------------------------------------------------
# Переключение языка интерфейса выполнено собственным механизмом
# (portal/i18n.py + portal/labels.py + portal.middleware.LanguageMiddleware):
# источник переводов — данные проекта (реестр страниц portal/pages.py и
# словарь подписей portal/labels.py), а не файлы .po/.mo.
#
# Список LANGUAGES ниже нужен административной панели: её переводы входят
# в поставку Django, и LanguageMiddleware активирует соответствующую локаль,
# поэтому /admin/ переключается тем же выбором языка.
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('ru', 'Русский'),
    ('zh-hans', '中文'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']


# --- Статические и медиафайлы --------------------------------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
