# Generated by Django 4.2.30 on 2026-10-01 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=128, verbose_name='название (рус.)')),
                ('name_zh', models.CharField(max_length=128, verbose_name='название (кит.)')),
                ('stage', models.CharField(choices=[('order', 'Заказ'), ('production', 'Производство'), ('shipment', 'Отгрузка'), ('customs', 'Таможня'), ('payment', 'Расчёт')], max_length=16, verbose_name='обязателен на этапе')),
            ],
            options={
                'verbose_name': 'тип документа',
                'verbose_name_plural': 'типы документов',
                'db_table': 'portal_doctype',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('file', models.FileField(upload_to='docs/%Y/%m', verbose_name='файл')),
                ('issuer', models.CharField(blank=True, max_length=128, verbose_name='кем выдан')),
                ('issued_date', models.DateField(verbose_name='дата выдачи')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='действителен до')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан'), ('uploaded', 'Загружен'), ('archived', 'В архиве'), ('expired', 'Просрочен')], default='uploaded', max_length=16, verbose_name='статус')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.doctype', verbose_name='тип документа')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='trading.order', verbose_name='заказ')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='logistics.shipment', verbose_name='партия')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'db_table': 'portal_document',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='DocRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('missing', 'Отсутствует'), ('provided', 'Предоставлен'), ('checked', 'Проверен')], default='missing', max_length=16, verbose_name='статус')),
                ('note', models.CharField(blank=True, max_length=191, verbose_name='примечание')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='documents.doctype', verbose_name='тип документа')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_requirements', to='documents.document', verbose_name='загруженный документ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_requirements', to='trading.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'требование к комплекту',
                'verbose_name_plural': 'требования к комплекту',
                'db_table': 'portal_docrequirement',
                'ordering': ['order', 'doc_type'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(max_length=16, verbose_name='вид объекта')),
                ('target_id', models.PositiveBigIntegerField(verbose_name='код объекта')),
                ('due_date', models.DateField(verbose_name='напоминание о дате')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('acked', 'Подтверждено'), ('canceled', 'Отменено')], default='pending', max_length=16, verbose_name='статус')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_reminders', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'напоминание о сроке',
                'verbose_name_plural': 'напоминания о сроках',
                'db_table': 'portal_deadlinereminder',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='проверено')),
                ('result', models.CharField(choices=[('passed', 'Пройдена'), ('issues', 'Есть замечания'), ('failed', 'Не пройдена')], max_length=16, verbose_name='результат')),
                ('note', models.TextField(blank=True, verbose_name='замечания')),
                ('checker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks', to=settings.AUTH_USER_MODEL, verbose_name='проверяющий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='trading.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'проверка соответствия',
                'verbose_name_plural': 'проверки соответствия',
                'db_table': 'portal_compliancecheck',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='номер')),
                ('kind', models.CharField(choices=[('conformity', 'Соответствия'), ('origin', 'Происхождения'), ('phyto', 'Карантинный'), ('quality', 'Качества')], max_length=16, verbose_name='вид')),
                ('issuer', models.CharField(max_length=128, verbose_name='орган выдачи')),
                ('issued_date', models.DateField(verbose_name='дата выдачи')),
                ('valid_until', models.DateField(verbose_name='действителен до')),
                ('fgis_no', models.CharField(blank=True, max_length=32, verbose_name='регистрация в ФГИС')),
                ('qr_data', models.CharField(blank=True, max_length=128, verbose_name='данные QR-кода')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='catalog.good', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'сертификат',
                'verbose_name_plural': 'сертификаты',
                'db_table': 'portal_certificate',
                'ordering': ['valid_until'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'valid_until'], name='portal_docu_status_0b8ef5_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('issued_date')), _connector='OR'), name='document_validity_not_inverted'),
        ),
        migrations.AddConstraint(
            model_name='docrequirement',
            constraint=models.UniqueConstraint(fields=('order', 'doc_type'), name='docrequirement_unique'),
        ),
    ]
