# Generated by Django 4.2.30 on 2026-10-01 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_kind', models.CharField(choices=[('rfq', 'Запрос'), ('quote', 'Предложение'), ('order', 'Заказ'), ('shipment', 'Партия'), ('incident', 'Инцидент')], max_length=16, verbose_name='тип объекта')),
                ('subject_id', models.PositiveBigIntegerField(verbose_name='код объекта')),
                ('subject_label', models.CharField(blank=True, max_length=128, verbose_name='обозначение объекта')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=8, verbose_name='статус')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='последнее сообщение')),
                ('participants', models.ManyToManyField(related_name='dialogs', to=settings.AUTH_USER_MODEL, verbose_name='участники')),
            ],
            options={
                'verbose_name': 'диалог',
                'verbose_name_plural': 'диалоги',
                'db_table': 'portal_dialog',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='текст')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('zh', '中文')], default='ru', max_length=2, verbose_name='язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.dialog', verbose_name='диалог')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'db_table': 'portal_message',
                'ordering': ['dialog', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(max_length=2, verbose_name='исходный язык')),
                ('target_language', models.CharField(max_length=2, verbose_name='язык перевода')),
                ('text', models.TextField(verbose_name='перевод')),
                ('engine', models.CharField(default='manual', max_length=32, verbose_name='движок перевода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='messaging.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'перевод',
                'verbose_name_plural': 'переводы',
                'db_table': 'portal_translation',
                'ordering': ['message', 'target_language'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attach/%Y/%m', verbose_name='файл')),
                ('owner_kind', models.CharField(max_length=16, verbose_name='тип владельца')),
                ('owner_id', models.PositiveBigIntegerField(verbose_name='код владельца')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='размер, байт')),
                ('mime_type', models.CharField(blank=True, max_length=96, verbose_name='MIME-тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='загружено')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'вложение',
                'verbose_name_plural': 'вложения',
                'db_table': 'portal_attachment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('message', 'target_language'), name='translation_message_target_unique'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['dialog', 'created_at'], name='portal_mess_dialog__7ee7a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='dialog',
            constraint=models.UniqueConstraint(fields=('subject_kind', 'subject_id'), name='dialog_subject_unique'),
        ),
    ]
