# Generated by Django 4.2.30 on 2026-10-01 03:31

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='номер')),
                ('title', models.CharField(max_length=191, verbose_name='заголовок')),
                ('source_kind', models.CharField(choices=[('order', 'Заказ'), ('rfq', 'Запрос'), ('document', 'Документ'), ('incident', 'Инцидент'), ('manual', 'Вручную')], default='manual', max_length=16, verbose_name='источник')),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='код источника')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='срок')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий')], default='normal', max_length=8, verbose_name='приоритет')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('canceled', 'Отменена')], default='new', max_length=16, verbose_name='статус')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'db_table': 'portal_task',
                'ordering': ['status', 'due_date'],
            },
            bases=(core.models.DocNumberMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'В приложении'), ('email', 'Электронная почта'), ('push', 'Push')], default='in_app', max_length=8, verbose_name='канал')),
                ('send_at', models.DateTimeField(verbose_name='время отправки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='отправлено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'напоминание задачи',
                'verbose_name_plural': 'напоминания задач',
                'db_table': 'portal_taskreminder',
                'ordering': ['send_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('rfq_answered', 'Ответ на запрос'), ('quote_changed', 'Изменение предложения'), ('order_changed', 'Изменение заказа'), ('doc_expiring', 'Истекает документ'), ('incident_new', 'Новый инцидент'), ('task_due', 'Срок задачи')], max_length=32, verbose_name='событие')),
                ('channel', models.CharField(choices=[('in_app', 'В приложении'), ('email', 'Электронная почта'), ('push', 'Push')], default='in_app', max_length=8, verbose_name='канал')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='включено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'настройка уведомления',
                'verbose_name_plural': 'настройки уведомлений',
                'db_table': 'portal_notificationsetting',
                'ordering': ['user', 'event'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32, verbose_name='тип')),
                ('title', models.CharField(max_length=191, verbose_name='заголовок')),
                ('body', models.TextField(blank=True, verbose_name='текст')),
                ('link', models.CharField(blank=True, max_length=191, verbose_name='ссылка перехода')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'db_table': 'portal_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='portal_task_assigne_a70280_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationsetting',
            constraint=models.UniqueConstraint(fields=('user', 'event', 'channel'), name='notifsetting_unique'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='portal_noti_recipie_275a38_idx'),
        ),
    ]
