# Generated by Django 4.2.30 on 2026-10-01 03:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$')], verbose_name='код')),
                ('name_ru', models.CharField(max_length=64, verbose_name='название (рус.)')),
                ('name_zh', models.CharField(max_length=64, verbose_name='название (кит.)')),
                ('symbol', models.CharField(max_length=4, verbose_name='символ')),
                ('decimals', models.PositiveSmallIntegerField(default=2, verbose_name='знаков после запятой')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюты',
                'db_table': 'portal_currency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('sku', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9-]{2,31}$', 'Артикул: заглавные буквы, цифры и дефис')], verbose_name='артикул (SKU)')),
                ('hs_code', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{4,12}$', 'Только цифры')], verbose_name='код ТН ВЭД')),
                ('name_ru', models.CharField(max_length=191, verbose_name='название (рус.)')),
                ('name_zh', models.CharField(max_length=191, verbose_name='название (кит.)')),
                ('brand', models.CharField(blank=True, max_length=64, verbose_name='торговая марка')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='срок хранения, сут')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Например: {"Мощность": "150 Вт"}', verbose_name='характеристики')),
                ('description_ru', models.TextField(blank=True, verbose_name='описание (рус.)')),
                ('description_zh', models.TextField(blank=True, verbose_name='описание (кит.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='в каталоге')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'portal_good',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=96, verbose_name='название (рус.)')),
                ('name_zh', models.CharField(max_length=96, verbose_name='название (кит.)')),
            ],
            options={
                'verbose_name': 'отрасль',
                'verbose_name_plural': 'отрасли',
                'db_table': 'portal_industry',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=32, verbose_name='название (рус.)')),
                ('name_zh', models.CharField(max_length=32, verbose_name='название (кит.)')),
                ('kind', models.CharField(choices=[('count', 'Штуки'), ('weight', 'Масса'), ('volume', 'Объём')], default='count', max_length=8, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'единица измерения',
                'verbose_name_plural': 'единицы измерения',
                'db_table': 'portal_uom',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='goods/%Y/%m', verbose_name='файл')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_main', models.BooleanField(default=False, verbose_name='главное изображение')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.good', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'изображение товара',
                'verbose_name_plural': 'изображения товаров',
                'db_table': 'portal_productimage',
                'ordering': ['good', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('box', 'Коробка'), ('pallet', 'Паллет'), ('bag', 'Мешок'), ('container', 'Контейнер')], default='box', max_length=16, verbose_name='тип упаковки')),
                ('units_per_pack', models.PositiveIntegerField(default=1, verbose_name='штук в упаковке')),
                ('unit_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='масса места, кг')),
                ('dims', models.CharField(blank=True, max_length=32, verbose_name='габариты (ДхШхВ), см')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='catalog.good', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'упаковка',
                'verbose_name_plural': 'упаковки',
                'db_table': 'portal_packaging',
                'ordering': ['good', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=96, verbose_name='название (рус.)')),
                ('name_zh', models.CharField(max_length=96, verbose_name='название (кит.)')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='уровень вложенности')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.goodcategory', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'категория товара',
                'verbose_name_plural': 'категории товаров',
                'db_table': 'portal_goodcategory',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='catalog.goodcategory', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='good',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='catalog.uom', verbose_name='единица измерения'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code2', models.CharField(max_length=2, unique=True, verbose_name='код ISO 3166-1 alpha-2')),
                ('name_ru', models.CharField(max_length=64, verbose_name='название (рус.)')),
                ('name_zh', models.CharField(max_length=64, verbose_name='название (кит.)')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=32, verbose_name='часовой пояс')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='catalog.currency', verbose_name='основная валюта')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
                'db_table': 'portal_country',
                'ordering': ['code2'],
            },
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('good',), name='productimage_single_main'),
        ),
        migrations.AddConstraint(
            model_name='packaging',
            constraint=models.CheckConstraint(check=models.Q(('units_per_pack__gte', 1)), name='packaging_units_positive'),
        ),
        migrations.AddConstraint(
            model_name='goodcategory',
            constraint=models.CheckConstraint(check=models.Q(('level__gte', 1), ('level__lte', 3)), name='goodcategory_level_1_3'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['category', 'is_active'], name='portal_good_categor_5af45f_idx'),
        ),
    ]
