# -*- coding: utf-8 -*-
"""Реестр страниц приложения (единый источник данных).

Единый реестр используется тремя потребителями:
  * portal/urls.py   — построение маршрутов;
  * portal/views.py  — прототипы представлений;
  * docs/pages.md и документ «Описание страниц приложения» — описание страниц.

Поля записи:
    name    — имя маршрута (url name);
    path    — шаблон URL (без ведущего слэша);
    view    — имя функции-представления в portal/views.py;
    module  — код модуля (M0..M11);
    ru/zh   — название страницы на русском и китайском;
    access  — режим доступа: public | auth | role;
    purpose — назначение страницы;
    content — основное содержание страницы;
    params  — описание параметров маршрута (или None).
"""

MODULES = [
    ("M0", "Общие страницы", "公共页面"),
    ("M1", "Предприятие и аккаунт", "企业与账号"),
    ("M2", "Товары", "商品管理"),
    ("M3", "Запросы и предложения", "询价与报价"),
    ("M4", "Заказы", "订单管理"),
    ("M5", "Логистика и пункты пропуска", "物流与口岸"),
    ("M6", "Документы и соответствие", "单证与合规"),
    ("M7", "Двуязычное общение", "双语沟通"),
    ("M8", "Задачи и напоминания", "任务与提醒"),
    ("M9", "Аналитика", "数据看板"),
    ("M10", "Расчёты и сверка", "结算与对账"),
    ("M11", "Администрирование", "系统管理"),
]

MODULE_BY_CODE = {code: (ru, zh) for code, ru, zh in MODULES}

PAGES = [
    # ---------------------------------------------------------- M0
    dict(name="index", path="", view="index_view", module="M0",
         ru="Главная страница", zh="首页",
         access="public",
         purpose="向未登录访客与已登录用户展示平台定位、核心能力与当前待办概览。",
         content="平台一句话定位、四类核心能力卡片、中俄贸易背景数据摘要、登录/注册入口；已登录时追加今日待办、异常订单、临期证书三张摘要卡。",
         params=None),
    dict(name="about", path="about/", view="about_view", module="M0",
         ru="О платформе", zh="关于平台",
         access="public",
         purpose="说明平台所处的产业链位置、四条业务边界与服务对象。",
         content="平台定位（贸易协同层）、不做的四件事（资金业务、报关代理、合规结论判定、无关个人信息采集）、三类服务对象。",
         params=None),
    dict(name="help", path="help/", view="help_view", module="M0",
         ru="Справка", zh="帮助与使用指南",
         access="public",
         purpose="提供按角色划分的操作指引与常见问题解答。",
         content="按角色（中方贸易商、中方业务员、俄方合作方、货代操作员）分类的操作步骤、术语表、常见问题。",
         params=None),
    dict(name="login", path="accounts/login/", view="login_view", module="M0",
         ru="Вход в систему", zh="登录",
         access="public",
         purpose="校验用户身份并建立登录会话。",
         content="账号与密码输入、记住登录状态、验证码登录切换、忘记密码入口；登录失败给出明确原因与剩余尝试次数。",
         params=None),
    dict(name="register", path="accounts/register/", view="register_view",
         module="M0", ru="Регистрация", zh="注册",
         access="public",
         purpose="创建个人账号并绑定所属企业主体。",
         content="手机号与邮箱注册（支持中国 +86 与俄罗斯 +7 区号）、密码强度校验、验证码倒计时、企业主体关联入口。",
         params=None),
    dict(name="logout", path="accounts/logout/", view="logout_view",
         module="M0", ru="Выход из системы", zh="退出登录",
         access="auth",
         purpose="结束当前会话并清理本地登录态。",
         content="退出确认提示；退出后跳转至首页。",
         params=None),

    # ---------------------------------------------------------- M1
    dict(name="enterprise_profile", path="enterprises/profile/",
         view="enterprise_profile_view", module="M1",
         ru="Профиль предприятия", zh="企业双语档案",
         access="auth",
         purpose="维护企业主体的中俄双语档案，作为单证与合同自动填充的数据源。",
         content="企业名称、统一社会信用代码/ИНН、注册地址、联系方式、银行信息；中俄双语字段并排填写，缺失项高亮提示补录。",
         params=None),
    dict(name="enterprise_verification", path="enterprises/verification/",
         view="enterprise_verification_view", module="M1",
         ru="Подтверждение субъекта", zh="主体认证",
         access="auth",
         purpose="提交并跟踪企业主体认证材料，控制未认证主体的功能范围。",
         content="营业执照或俄方登记文件上传、字段识别结果确认、审核状态跟踪（待提交/审核中/已通过/已驳回）、驳回原因展示。",
         params=None),
    dict(name="enterprise_members", path="enterprises/members/",
         view="enterprise_members_view", module="M1",
         ru="Сотрудники и роли", zh="成员与角色管理",
         access="role",
         purpose="管理企业组织架构、成员账号与角色分配。",
         content="成员列表（姓名、角色、状态、最近登录）、角色分配、账号停用与交接；仅业务负责人与管理员可见。",
         params=None),
    dict(name="enterprise_invitations", path="enterprises/invitations/",
         view="enterprise_invitations_view", module="M1",
         ru="Приглашение партнёров", zh="协作者邀请",
         access="auth",
         purpose="邀请俄方合作方或货代操作员加入指定订单的协同范围。",
         content="邀请对象类型选择、协同范围（按订单或按批次）、有效期设置、邀请链接与二维码、邀请状态跟踪。",
         params=None),

    # ---------------------------------------------------------- M2
    dict(name="goods_list", path="goods/", view="goods_list_view",
         module="M2", ru="Список товаров", zh="商品列表",
         access="auth",
         purpose="按品类、状态与关键词检索本企业商品卡片。",
         content="卡片化列表（图片、中俄双语标题、规格摘要、合规属性标识）、常用筛选标签、排序、批量操作入口。",
         params=None),
    dict(name="goods_detail", path="goods/<int:pk>/", view="goods_detail_view",
         module="M2", ru="Карточка товара", zh="商品详情",
         access="auth",
         purpose="展示商品完整信息、合规属性与历史版本。",
         content="中俄双语标题与描述、规格参数、包装信息、图片集、HS 编码与合规属性、关联证书、版本历史与差异对比。",
         params="pk — идентификатор товара"),
    dict(name="goods_form", path="goods/new/", view="goods_form_view",
         module="M2", ru="Создание и редактирование товара", zh="新建/编辑商品",
         access="auth",
         purpose="录入或修改商品卡片，支持中俄双语字段。",
         content="按基本信息、规格、包装、合规属性分四步填写，每步不超过 5 个字段；顶部进度指示；草稿自动保存。",
         params=None),

    # ---------------------------------------------------------- M3
    dict(name="rfq_list", path="rfqs/", view="rfq_list_view", module="M3",
         ru="Список запросов", zh="询价单列表",
         access="auth",
         purpose="集中查看本企业发出与收到的询价单及其响应状态。",
         content="按“我发起的 / 待我响应 / 已关闭”分组；列表项展示商品、数量、目标价区间、期望交期与剩余响应时间。",
         params=None),
    dict(name="rfq_create", path="rfqs/new/", view="rfq_create_view",
         module="M3", ru="Создание запроса", zh="发起询价",
         access="auth",
         purpose="由俄方合作方发起询价，明确数量、目标价与交期。",
         content="商品选择、数量、目标价区间、期望交期、收货地、补充说明；一屏可填完，提交后即时通知中方。",
         params=None),
    dict(name="rfq_detail", path="rfqs/<int:pk>/", view="rfq_detail_view",
         module="M3", ru="Карточка запроса", zh="询价单详情",
         access="auth",
         purpose="展示询价单全部条款与关联报价，支持直接响应。",
         content="询价条款、发起方与时间、关联报价列表、状态流转记录、响应入口与会话入口。",
         params="pk — идентификатор запроса"),
    dict(name="quote_list", path="quotes/", view="quote_list_view",
         module="M3", ru="Список предложений", zh="报价单列表",
         access="auth",
         purpose="查看本企业发出与收到的报价单及其版本与有效期。",
         content="列表项展示商品、单价与币种、贸易术语、有效期剩余天数、版本号；临期报价高亮提示。",
         params=None),
    dict(name="quote_detail", path="quotes/<int:pk>/", view="quote_detail_view",
         module="M3", ru="Карточка предложения", zh="报价单详情",
         access="auth",
         purpose="展示报价全部条款、阶梯价与版本历史，支持转为订单。",
         content="单价、币种、阶梯价、交期、贸易术语、有效期、备注；版本历史与差异对比；发出后不可直接修改，修改生成新版本。",
         params="pk — идентификатор предложения"),

    # ---------------------------------------------------------- M4
    dict(name="order_list", path="orders/", view="order_list_view",
         module="M4", ru="Список заказов", zh="订单列表",
         access="auth",
         purpose="按状态、通道与时间检索订单，快速定位异常与超期订单。",
         content="卡片化列表（订单号、对方企业、当前状态标签、关键时间、下一步动作）、状态筛选、异常订单置顶、导出入口。",
         params=None),
    dict(name="order_detail", path="orders/<int:pk>/", view="order_detail_view",
         module="M4", ru="Карточка заказа", zh="订单详情",
         access="auth",
         purpose="以“状态区 + 里程碑时间轴 + 操作区”三段式结构回答订单当前进度与下一步动作。",
         content="顶部状态区（当前状态、下一步动作、责任方）；中部里程碑时间轴（节点、时间、操作人、凭证缩略图）；底部操作区（按角色与状态动态给出可执行动作）。",
         params="pk — идентификатор заказа"),
    dict(name="order_milestones", path="orders/<int:pk>/milestones/",
         view="order_milestones_view", module="M4",
         ru="Этапы исполнения заказа", zh="履约里程碑",
         access="auth",
         purpose="按时间顺序登记与查看订单履约节点，形成可追溯的证据链。",
         content="节点登记表单（节点类型、时间、操作人、说明、凭证上传）、时间轴全量展示、凭证查看与下载。",
         params="pk — идентификатор заказа"),
    dict(name="order_changes", path="orders/<int:pk>/changes/",
         view="order_changes_view", module="M4",
         ru="Изменения заказа", zh="订单变更单",
         access="auth",
         purpose="以变更单方式记录数量、价格、交期与收货信息的调整，保留原值。",
         content="变更项选择、变更前后值对照、变更原因、双方确认状态；未确认前原条款继续有效。",
         params="pk — идентификатор заказа"),

    # ---------------------------------------------------------- M5
    dict(name="shipment_list", path="shipments/", view="shipment_list_view",
         module="M5", ru="Партии и перевозки", zh="运输批次列表",
         access="auth",
         purpose="按批次跟踪货物运输状态与所属通道。",
         content="批次列表（批次号、运输方式、通道、口岸、当前节点、预计到达时间）；支持按通道与口岸筛选。",
         params=None),
    dict(name="shipment_detail", path="shipments/<int:pk>/",
         view="shipment_detail_view", module="M5",
         ru="Карточка партии", zh="运输节点登记",
         access="auth",
         purpose="登记提货至派送的各运输节点并上传凭证。",
         content="运输方式与运单号、箱号与封号（支持扫码录入）、节点登记表单、时效偏差提示、凭证列表。",
         params="pk — идентификатор партии"),
    dict(name="exception_list", path="exceptions/", view="exception_list_view",
         module="M5", ru="Список инцидентов", zh="在途异常列表",
         access="auth",
         purpose="集中查看在途异常及其处置进展。",
         content="异常列表（异常分类、发生节点、上报人、上报时间、处置状态）；未处置异常置顶并高亮。",
         params=None),
    dict(name="exception_create", path="exceptions/new/",
         view="exception_create_view", module="M5",
         ru="Регистрация инцидента", zh="上报在途异常",
         access="auth",
         purpose="在现场三步内完成异常上报，自动附带时间与位置。",
         content="异常分类选择、情况说明、拍照上传（自动压缩并记录时间与位置）、关联订单与批次；离线可提交，恢复网络后自动同步。",
         params=None),

    # ---------------------------------------------------------- M6
    dict(name="documents_list", path="documents/", view="documents_list_view",
         module="M6", ru="Реестр документов", zh="单证清单",
         access="auth",
         purpose="按运输方式与商品品类展示订单所需单证清单及其齐备情况。",
         content="清单项（单证类型、是否必需、是否已上传、有效版本、上传人、上传时间）；缺件项高亮并给出补件入口。",
         params=None),
    dict(name="documents_upload", path="documents/upload/",
         view="documents_upload_view", module="M6",
         ru="Загрузка документов", zh="单证上传",
         access="auth",
         purpose="以拍照、相册或文件三种方式上传单证，并保留版本。",
         content="上传方式选择、单证类型指定、文件类型与大小校验、上传进度与断点续传、版本标注（有效版本唯一）。",
         params=None),
    dict(name="certificates_list", path="certificates/",
         view="certificates_list_view", module="M6",
         ru="Срок действия сертификатов", zh="证书有效期管理",
         access="auth",
         purpose="登记证书信息并按 60/30/7 天分级提醒到期风险。",
         content="证书列表（编号、签发方、生效日、到期日、剩余天数、关联商品与订单）；临期与过期按颜色分级；关联订单高亮。",
         params=None),
    dict(name="compliance_check", path="compliance/self-check/",
         view="compliance_check_view", module="M6",
         ru="Самопроверка соответствия", zh="合规自查表",
         access="auth",
         purpose="按清单逐项自查并留痕，作为发运前的检查依据。",
         content="按运输方式生成的检查项清单、逐项勾选、不通过项填写原因、提交后生成留痕记录；平台只提示不判定结论。",
         params=None),

    # ---------------------------------------------------------- M7
    dict(name="message_list", path="messages/", view="message_list_view",
         module="M7", ru="Список диалогов", zh="会话列表",
         access="auth",
         purpose="按业务对象分组查看会话，避免沟通脱离业务上下文。",
         content="会话列表（关联订单/批次/单证/对账单、对方企业、最后一条消息摘要、未读数）；未读会话置顶。",
         params=None),
    dict(name="message_detail", path="messages/<int:pk>/",
         view="message_detail_view", module="M7",
         ru="Диалог", zh="会话详情",
         access="auth",
         purpose="在业务对象上下文中进行中俄双语沟通并留存记录。",
         content="消息流、结构化消息模板选择、翻译辅助（标注“机器辅助翻译”并要求发送方确认）、术语库提示、文件与图片消息、按业务对象导出沟通记录。",
         params="pk — идентификатор диалога"),

    # ---------------------------------------------------------- M8
    dict(name="task_board", path="tasks/", view="task_board_view", module="M8",
         ru="Доска задач", zh="任务看板",
         access="auth",
         purpose="按“待我处理 / 我发起的 / 已超时”分组呈现任务并支持筛选。",
         content="三组看板列、任务卡片（标题、关联业务对象、责任人、剩余时限）、超时项置顶并高亮、筛选与批量操作。",
         params=None),
    dict(name="task_detail", path="tasks/<int:pk>/", view="task_detail_view",
         module="M8", ru="Карточка задачи", zh="任务详情",
         access="auth",
         purpose="展示任务详情、处理记录与升级链路。",
         content="任务描述、关联业务对象、责任人、响应时限、处理记录、确认接收与转派、超时升级记录。",
         params="pk — идентификатор задачи"),
    dict(name="notification_settings", path="notifications/settings/",
         view="notification_settings_view", module="M8",
         ru="Настройки уведомлений", zh="提醒与免打扰设置",
         access="auth",
         purpose="配置各类事件的推送渠道、优先级与免打扰时段。",
         content="事件类型与推送开关、推送渠道（应用内/短信/邮件）、免打扰时段（按各自本地时间生效）、语言与时区切换入口。",
         params=None),

    # ---------------------------------------------------------- M9
    dict(name="dashboard", path="dashboard/", view="dashboard_view",
         module="M9", ru="Панель исполнения", zh="履约看板",
         access="auth",
         purpose="以摘要卡与紧凑图表呈现履约整体状况。",
         content="在途订单数量、状态分布、平均履约周期、超期订单清单；今日待办、异常订单、临期证书三张摘要卡，卡内数字即入口。",
         params=None),
    dict(name="dashboard_logistics", path="dashboard/logistics/",
         view="dashboard_logistics_view", module="M9",
         ru="Сроки и затраты", zh="时效与成本统计",
         access="auth",
         purpose="按通道、口岸与品类统计平均时效与费用构成。",
         content="通道时效对比、口岸平均通关时长、费用构成（运费、报关费、仓储费、换装费）；支持按时间区间筛选与导出。",
         params=None),
    dict(name="dashboard_compliance", path="dashboard/compliance/",
         view="dashboard_compliance_view", module="M9",
         ru="Риски соответствия", zh="合规风险看板",
         access="auth",
         purpose="汇总临期与过期证书、缺件订单与待完成自查项。",
         content="风险清单按严重度排序（过期证书、临期证书、缺件订单、未完成自查）、一键跳转至处理页、导出风险报告。",
         params=None),

    # ---------------------------------------------------------- M10
    dict(name="statement_list", path="statements/", view="statement_list_view",
         module="M10", ru="Список счетов", zh="账单列表",
         access="auth",
         purpose="依据订单与费用归集生成账单并跟踪确认状态。",
         content="账单列表（关联订单、货值、运费、报关费、仓储费、合计、确认状态）；支持按时间区间与对方企业筛选。",
         params=None),
    dict(name="statement_detail", path="statements/<int:pk>/",
         view="statement_detail_view", module="M10",
         ru="Сверка расчётов", zh="对账详情",
         access="auth",
         purpose="逐项确认账单条目，标记差异并记录争议过程。",
         content="明细逐项确认、差异标记与原因填写、付款节点状态登记（已申请/已汇出/已到账，双方分别确认）、争议留痕与导出。",
         params="pk — идентификатор счёта"),

    # ---------------------------------------------------------- M11
    dict(name="audit_log_list", path="system/audit-logs/",
         view="audit_log_list_view", module="M11",
         ru="Журнал аудита", zh="审计日志",
         access="role",
         purpose="查询登录、权限变更、状态迁移与数据导出等关键操作记录。",
         content="日志列表（操作人、时间、对象、操作类型、前后值）、按对象与时间检索、导出；日志只可查询不可删除。",
         params=None),
    dict(name="dictionary_list", path="system/dictionaries/",
         view="dictionary_list_view", module="M11",
         ru="Справочники", zh="基础字典维护",
         access="role",
         purpose="维护口岸、通道、贸易术语、单证类型与异常原因分类等基础字典。",
         content="字典分类树、词条增删改、启用与停用、双语词条维护；变更写入审计日志。",
         params=None),
    dict(name="admin_index", path="admin/", view=None, module="M11",
         ru="Административная панель Django", zh="Django 管理后台",
         access="role",
         purpose="由 Django 框架自带的管理后台提供数据维护能力。",
         content="模型注册、数据增删改查、用户与权限管理；由 django.contrib.admin 提供，不另行开发。",
         params=None),
]

PAGE_BY_NAME = {p["name"]: p for p in PAGES}
PAGE_BY_VIEW = {p["view"]: p for p in PAGES if p["view"]}


def pages_of(module_code):
    return [p for p in PAGES if p["module"] == module_code]


def url_of(page):
    """Полный URL страницы для документации (с ведущим слэшем)."""
    return "/" + page["path"]
